#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

function watch {
  lume --watch "$@"
}

function build {
  lume "$@"
}

function update-deps {
  udd _config.js _plugins/*.js
}

function sync {
  lume "$@"
  rsync -a --partial --progress _site/ fserb.com:fserb/
}

function help {
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | grep -v "^_" | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-help}"
